export const dayOrder = {
    Domingo: 0,
    Lunes: 1,
    Martes: 2,
    Miercoles: 3,
    Jueves: 4,
    Viernes: 5,
    Sabado: 6,
};

export const monthsOrder = [
    'Jan',
    'Feb',
    'Mar',
    'Abr',
    'May',
    'Jun',
    'Jul',
    'Ago',
    'Sep',
    'Oct',
    'Nov',
    'Dic',
];


export const stopWords = [
    "a", "al", "algo", "algún", "alguna", "algunas", "alguno", "algunos",
    "ante", "antes", "como", "con", "contra", "cual", "cuando", "de",
    "del", "desde", "donde", "durante", "e", "el", "ella", "ellas", "ellos",
    "en", "entre", "era", "erais", "éramos", "eran", "eras", "eres", "es",
    "esa", "esas", "ese", "eso", "esos", "esta", "estaba", "estabais",
    "estábamos", "estaban", "estabas", "estad", "estada", "estadas",
    "estado", "estados", "estamos", "estando", "estar", "estaremos",
    "estará", "estarán", "estarás", "estaré", "estaréis", "estaría",
    "estaríais", "estaríamos", "estarían", "estarías", "estas", "este",
    "esté", "estéis", "estemos", "estén", "estés", "esto", "estos", "estoy",
    "etc", "había", "habíais", "habíamos", "habían", "habías", "habéis",
    "habiendo", "haber", "habrá", "habrán", "habrás", "habré", "habréis",
    "habría", "habríais", "habríamos", "habrían", "habrías", "han", "has",
    "hasta", "hay", "haya", "hayamos", "hayan", "hayas", "he", "hemos",
    "hube", "hubiera", "hubierais", "hubiéramos", "hubieran", "hubieras",
    "hubieron", "hubiese", "hubieseis", "hubiésemos", "hubiesen", "hubieses",
    "habiendo", "habido", "habéis", "hubo", "la", "las", "lo", "los",
    "más", "me", "mi", "mis", "mucho", "muchos", "muy", "nada", "ni",
    "ningún", "ninguna", "ningunas", "ninguno", "ningunos", "no", "nos",
    "nosotras", "nosotros", "nuestra", "nuestras", "nuestro", "nuestros",
    "o", "os", "otra", "otras", "otro", "otros", "para", "pero", "poca",
    "pocas", "poco", "pocos", "por", "porque", "que", "quien", "quienes",
    "qué", "se", "sea", "seáis", "seamos", "sean", "seas", "ser", "seremos",
    "será", "serán", "serás", "seré", "seréis", "sería", "seríais",
    "seríamos", "serían", "serías", "si", "sido", "siendo", "sin", "sobre",
    "sois", "somos", "son", "soy", "su", "sus", "suya", "suyas", "suyo",
    "suyos", "también", "tanto", "te", "tened", "tenemos", "tenga",
    "tengáis", "tengamos", "tengan", "tengas", "tengo", "tenida",
    "tenidas", "tenido", "tenidos", "teniendo", "tenéis", "tenía",
    "teníais", "teníamos", "tenían", "tenías", "ti", "tiene", "tienen",
    "tienes", "todo", "todos", "tu", "tus", "tuve", "tuviera", "tuvierais",
    "tuviéramos", "tuvieran", "tuvieras", "tuvieron", "tuviese",
    "tuvieseis", "tuviésemos", "tuviesen", "tuvieses", "tenido", "tuvo",
    "tuya", "tuyas", "tuyo", "tuyos", "un", "una", "unas", "uno", "unos",
    "vosotras", "vosotros", "vuestra", "vuestras", "vuestro", "vuestros",
    "y", "ya", "yo", 
  ];